[package]
name                  = "oxc_linter"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_allocator   = { workspace = true }
oxc_parser      = { workspace = true }
oxc_span        = { workspace = true }
oxc_ast         = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_macros      = { workspace = true }
oxc_semantic    = { workspace = true }
oxc_syntax      = { workspace = true }
oxc_formatter   = { workspace = true }
oxc_resolver    = { workspace = true }

dashmap     = { workspace = true }
lazy_static = { workspace = true }                                    # used in oxc_macros
miette      = { workspace = true, features = ["fancy-no-backtrace"] }
num-traits  = { workspace = true }
phf         = { workspace = true, features = ["macros"] }
rayon       = { workspace = true }
regex       = { workspace = true }
rustc-hash  = { workspace = true }
serde_json  = { workspace = true }

rust-lapper = "1.1.0"

[dev-dependencies]
miette = { workspace = true, features = ["fancy-no-backtrace"] }
insta  = { version = "1.28.0", features = ["glob"] }
